spring.datasource.url=jdbc:postgresql://${PROD_DB_URL}/${PROD_DB_NAME}
spring.datasource.username=${PROD_DB_USERNAME}
spring.datasource.password=${PROD_DB_PASSWORD}

discord.bot.token=${PROD_BOT_TOKEN}