--
-- PostgreSQL database dump
--

-- Dumped from database version 17.9
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: associate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.associate (
    id_discord_message bigint NOT NULL,
    id_label bigint NOT NULL
);


--
-- Name: bind; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bind (
    id_file bigint NOT NULL,
    id_label bigint NOT NULL
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category (
    id_category bigint NOT NULL,
    name character varying(255),
    discord_category_id_disc_category bigint
);


--
-- Name: category_id_category_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.category ALTER COLUMN id_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discord_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_category (
    id_disc_category bigint NOT NULL,
    name character varying(255)
);


--
-- Name: discord_channel; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_channel (
    id_discord_channel bigint NOT NULL,
    name character varying(255),
    type character varying(255),
    id_disc_category bigint,
    id_label bigint,
    CONSTRAINT discord_channel_type_check CHECK (((type)::text = ANY ((ARRAY['TEXT'::character varying, 'PRIVATE'::character varying, 'VOICE'::character varying, 'GROUP'::character varying, 'CATEGORY'::character varying, 'NEWS'::character varying, 'STAGE'::character varying, 'GUILD_NEWS_THREAD'::character varying, 'GUILD_PUBLIC_THREAD'::character varying, 'GUILD_PRIVATE_THREAD'::character varying, 'GUILD_DIRECTORY'::character varying, 'FORUM'::character varying, 'MEDIA'::character varying, 'UNKNOWN'::character varying])::text[])))
);


--
-- Name: discord_comment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_comment (
    id_discord_comment bigint NOT NULL,
    id_discord_message bigint,
    id_file bigint
);


--
-- Name: discord_message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_message (
    id_discord_message bigint NOT NULL,
    id_discord_channel bigint,
    id_discord_message_data bigint,
    id_discord_user bigint
);


--
-- Name: discord_message_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_message_data (
    id_discord_message_data bigint NOT NULL,
    content character varying(255)
);


--
-- Name: discord_message_data_id_discord_message_data_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.discord_message_data ALTER COLUMN id_discord_message_data ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.discord_message_data_id_discord_message_data_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: discord_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.discord_user (
    id_discord_user bigint NOT NULL,
    name character varying(255)
);


--
-- Name: drive_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drive_file (
    id_file bigint NOT NULL,
    name character varying(255),
    path character varying(255),
    id_discord_message bigint,
    id_discord_user bigint NOT NULL,
    id_drive_folder bigint NOT NULL
);


--
-- Name: drive_folder; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.drive_folder (
    id_folder bigint NOT NULL,
    name character varying(255),
    path character varying(255)
);


--
-- Name: label; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.label (
    id_label bigint NOT NULL,
    name character varying(255)
);


--
-- Name: label_id_label_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.label ALTER COLUMN id_label ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.label_id_label_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: message; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.message (
    id_discord_message bigint NOT NULL,
    id_file bigint
);


--
-- Name: possess; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.possess (
    id_category bigint NOT NULL,
    id_label bigint NOT NULL
);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id_category);


--
-- Name: discord_category discord_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_category
    ADD CONSTRAINT discord_category_pkey PRIMARY KEY (id_disc_category);


--
-- Name: discord_channel discord_channel_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_channel
    ADD CONSTRAINT discord_channel_pkey PRIMARY KEY (id_discord_channel);


--
-- Name: discord_comment discord_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_comment
    ADD CONSTRAINT discord_comment_pkey PRIMARY KEY (id_discord_comment);


--
-- Name: discord_message_data discord_message_data_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_message_data
    ADD CONSTRAINT discord_message_data_pkey PRIMARY KEY (id_discord_message_data);


--
-- Name: discord_message discord_message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_message
    ADD CONSTRAINT discord_message_pkey PRIMARY KEY (id_discord_message);


--
-- Name: discord_user discord_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_user
    ADD CONSTRAINT discord_user_pkey PRIMARY KEY (id_discord_user);


--
-- Name: drive_file drive_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_file
    ADD CONSTRAINT drive_file_pkey PRIMARY KEY (id_file);


--
-- Name: drive_folder drive_folder_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_folder
    ADD CONSTRAINT drive_folder_pkey PRIMARY KEY (id_folder);


--
-- Name: label label_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label
    ADD CONSTRAINT label_pkey PRIMARY KEY (id_label);


--
-- Name: message message_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id_discord_message);


--
-- Name: category uk2qbqv93jvtxlrxbpnuv1xxlq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk2qbqv93jvtxlrxbpnuv1xxlq UNIQUE (discord_category_id_disc_category);


--
-- Name: category uk46ccwnsi9409t36lurvtyljak; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name);


--
-- Name: label ukdefh0r2wr6e5g7vu7vanv4pxa; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label
    ADD CONSTRAINT ukdefh0r2wr6e5g7vu7vanv4pxa UNIQUE (name);


--
-- Name: message ukfob45yvao8lij0xrietifqgdr; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT ukfob45yvao8lij0xrietifqgdr UNIQUE (id_file);


--
-- Name: discord_category ukfyba31m6w2n14ejwuapfgb4k; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_category
    ADD CONSTRAINT ukfyba31m6w2n14ejwuapfgb4k UNIQUE (name);


--
-- Name: drive_folder uki9th3b20tv9n5ykjk3gfc2803; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_folder
    ADD CONSTRAINT uki9th3b20tv9n5ykjk3gfc2803 UNIQUE (name);


--
-- Name: drive_folder ukwt3g58u1s8kdwqsg0d3mnvm6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_folder
    ADD CONSTRAINT ukwt3g58u1s8kdwqsg0d3mnvm6 UNIQUE (path);


--
-- Name: drive_file fk3xn8iqi6yws88t85ieh033ghd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_file
    ADD CONSTRAINT fk3xn8iqi6yws88t85ieh033ghd FOREIGN KEY (id_drive_folder) REFERENCES public.drive_folder(id_folder);


--
-- Name: category fk7f87tsgaoo2trd4caacfvww1w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT fk7f87tsgaoo2trd4caacfvww1w FOREIGN KEY (discord_category_id_disc_category) REFERENCES public.discord_category(id_disc_category);


--
-- Name: message fk866ni4csq9ko3injhioe6sa6s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk866ni4csq9ko3injhioe6sa6s FOREIGN KEY (id_discord_message) REFERENCES public.discord_message(id_discord_message);


--
-- Name: message fk8xacwmdggnvkltgti4q821e8v; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.message
    ADD CONSTRAINT fk8xacwmdggnvkltgti4q821e8v FOREIGN KEY (id_file) REFERENCES public.drive_file(id_file);


--
-- Name: discord_comment fk9agfyvkbd2iqf60rhgkox4yc3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_comment
    ADD CONSTRAINT fk9agfyvkbd2iqf60rhgkox4yc3 FOREIGN KEY (id_discord_message) REFERENCES public.discord_message(id_discord_message);


--
-- Name: bind fkbhe2jkwpua9kx8scx73hjioqa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bind
    ADD CONSTRAINT fkbhe2jkwpua9kx8scx73hjioqa FOREIGN KEY (id_label) REFERENCES public.label(id_label);


--
-- Name: possess fkid84e7y2meqx9vljc8j0c4p9d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.possess
    ADD CONSTRAINT fkid84e7y2meqx9vljc8j0c4p9d FOREIGN KEY (id_category) REFERENCES public.category(id_category);


--
-- Name: drive_file fkl736v7bea5dcld11wexp9hyca; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_file
    ADD CONSTRAINT fkl736v7bea5dcld11wexp9hyca FOREIGN KEY (id_discord_message) REFERENCES public.discord_message(id_discord_message);


--
-- Name: possess fkle36w9aquyol6n8k45yddeck7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.possess
    ADD CONSTRAINT fkle36w9aquyol6n8k45yddeck7 FOREIGN KEY (id_label) REFERENCES public.label(id_label);


--
-- Name: bind fklicb28gcqdu09dkbc5nixg4as; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bind
    ADD CONSTRAINT fklicb28gcqdu09dkbc5nixg4as FOREIGN KEY (id_file) REFERENCES public.drive_file(id_file);


--
-- Name: drive_file fklv323qkqc953ncegd2f6lcvuo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.drive_file
    ADD CONSTRAINT fklv323qkqc953ncegd2f6lcvuo FOREIGN KEY (id_discord_user) REFERENCES public.discord_user(id_discord_user);


--
-- Name: discord_comment fkm7onfd25j7wj2c0bgdupmanj9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_comment
    ADD CONSTRAINT fkm7onfd25j7wj2c0bgdupmanj9 FOREIGN KEY (id_discord_comment) REFERENCES public.discord_message(id_discord_message);


--
-- Name: discord_channel fkmewu893jii6pfmd46mc3v6ptp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_channel
    ADD CONSTRAINT fkmewu893jii6pfmd46mc3v6ptp FOREIGN KEY (id_label) REFERENCES public.label(id_label);


--
-- Name: associate fkmt3lu85tj7ypnn8n0i9d05x1s; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.associate
    ADD CONSTRAINT fkmt3lu85tj7ypnn8n0i9d05x1s FOREIGN KEY (id_discord_message) REFERENCES public.message(id_discord_message);


--
-- Name: discord_comment fkpx4nxvag4k0ayig6vxacvmkwv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_comment
    ADD CONSTRAINT fkpx4nxvag4k0ayig6vxacvmkwv FOREIGN KEY (id_file) REFERENCES public.drive_file(id_file);


--
-- Name: discord_message fkqncdn78nrdprrqdkaxcf0hj0d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_message
    ADD CONSTRAINT fkqncdn78nrdprrqdkaxcf0hj0d FOREIGN KEY (id_discord_channel) REFERENCES public.discord_channel(id_discord_channel);


--
-- Name: associate fkr06toh5nhdurc294a699201i3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.associate
    ADD CONSTRAINT fkr06toh5nhdurc294a699201i3 FOREIGN KEY (id_label) REFERENCES public.label(id_label);


--
-- Name: discord_message fkr7t2uavfr0vr7fam57ftwuvun; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_message
    ADD CONSTRAINT fkr7t2uavfr0vr7fam57ftwuvun FOREIGN KEY (id_discord_user) REFERENCES public.discord_user(id_discord_user);


--
-- Name: discord_channel fkt9slsfxj8c9jq5my3f47wtw7o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_channel
    ADD CONSTRAINT fkt9slsfxj8c9jq5my3f47wtw7o FOREIGN KEY (id_disc_category) REFERENCES public.discord_category(id_disc_category);


--
-- Name: discord_message fktapvkcii63y60d8le3ubsyqbl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.discord_message
    ADD CONSTRAINT fktapvkcii63y60d8le3ubsyqbl FOREIGN KEY (id_discord_message_data) REFERENCES public.discord_message_data(id_discord_message_data);


--
-- PostgreSQL database dump complete
--


